lime/board/api/urls.py
from django.urls import path
from . import views

app_name = 'board-api'

urlpatterns = [
	# BOARD ENDPOINTS
    path('boards/', views.BoardListCreateAPIView.as_view(), name='board_list'),
    path('boards/<int:pk>', views.BoardDetailAPIView.as_view(), name='board_detail'),
    # TASK ENDPOINTS
    path('tasks/', views.TaskListCreateAPIView.as_view(), name='task_list'),
    path('tasks/<int:pk>', views.TaskDetailAPIView.as_view(), name='task_detail'),
]

lime/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    #  BOARDS
    path('', views.BoardListView.as_view(), name='board_list'),
    path('board_create/', views.BoardCreateView.as_view(), name='board_create'),
    path('<int:pk>', views.BoardDetailView.as_view(), name='board_detail'),
    #  TASKS
    path('task_update/<int:pk>', views.TaskUpdateView.as_view(), name='task_edit'),
    path('task_move/<int:pk>', views.TaskMoveView.as_view(), name='task_move'),
    path('task_delete/<int:pk>', views.TaskDeleteView.as_view(), name='task_delete'),
    path('task_create/<int:board_pk>', views.TaskCreateView.as_view(), name='task_create'),
]

lime/lime/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('board/', include('board.urls')),
    path('api/', include('board.api.urls')),
]

lime/board/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from django.utils.safestring import mark_safe

User = get_user_model()


class Board(models.Model):
    title = models.CharField(max_length=255, null=True)
    create_time = models.DateTimeField(auto_now_add=True)
    users = models.ManyToManyField(User, related_name='boards', blank=True)
    is_active = models.BooleanField(default=True)

    @mark_safe
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:board_detail', kwargs={'pk': self.id})


class Task(models.Model):

    STATUS = [
        ('TD', 'TO DO'),
        ('PR', 'In progress'),
        ('DN', 'Done'),
    ]

    title = models.CharField(max_length=150, null=True)
    text = models.TextField(max_length=255)
    status = models.CharField(max_length=2, choices=STATUS, default='TD')
    create_time = models.DateTimeField(auto_now_add=True, null=True)
    update_time = models.DateTimeField(auto_now=True, null=True)
    board = models.ForeignKey(Board, related_name='tasks', null=True, on_delete=models.CASCADE)

    @mark_safe
    def __str__(self):
        return self.title

lime/lime/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    model = User

lime/board/api/views.py
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.authentication import SessionAuthentication
from rest_framework.generics import ListCreateAPIView, RetrieveDestroyAPIView

# from django.shortcuts import get_object_or_404

from . serializers import BoardSerializer, TaskSerializer
from board.models import Board, Task


class BoardListCreateAPIView(ListCreateAPIView):
	authentication_classes = [SessionAuthentication]
	permissions_classes = [AllowAny]
	serializer_class = BoardSerializer
	queryset = Board.objects.all()
	ordering_fields = ('title', 'create_date')
	search_fields = ('title', 'tasks__title')

	def perform_create(self, serializer):
		serializer.save(users=[self.request.user])

	def post(self, request, *args, **kwargs):
		return self.create(request, *args, **kwargs)


class BoardDetailAPIView(RetrieveDestroyAPIView):
	authentication_classes = [SessionAuthentication]
	permissions_classes = [AllowAny]
	serializer_class = BoardSerializer
	queryset = Board.objects.all()

	def perform_destroy(self, instance):
		if instance is not None:
			return instance.delete()
		else:
			return None

	def delete(self, request, *args, **kwargs):
		return self.destroy(request, *args, **kwargs)


class TaskListCreateAPIView(ListCreateAPIView):
	authentication_classes = [SessionAuthentication]
	permissions_classes = [AllowAny]
	serializer_class = TaskSerializer
	queryset = Task.objects.all()
	ordering_fields = ('title', 'create_date')
	search_fields = ('title')

	def post(self, request, *args, **kwargs):
		return self.create(request, *args, **kwargs)


class TaskDetailAPIView(RetrieveDestroyAPIView):
	authentication_classes = [SessionAuthentication]
	permissions_classes = [AllowAny]
	serializer_class = TaskSerializer
	queryset = Task.objects.all()	

lime/board/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import (DetailView, ListView,
                                  CreateView, DeleteView,
                                  UpdateView)
#  Models
from .models import Board, Task


class BoardListView(ListView):
    model = Board
    template_name = 'base_board.html'
    http_method_names = ['get']

    def get_queryset(self):
        qs = self.request.user.boards.filter(is_active=True).order_by('-create_time')
        return qs


class BoardCreateView(CreateView):
    model = Board
    fields = ['title']
    template_name = 'task_create.html'

    def form_valid(self, form):
        form.save()
        form.instance.users.set([self.request.user])
        return super().form_valid(form)


class BoardDetailView(DetailView):
    model = Board
    template_name = 'board_detail.html'
    http_method_names = ['get']

    def get_context_data(self, **kwargs):
        """
        Create QS's for each column to avoid multiple fetching in the template.
        """
        context = super().get_context_data(**kwargs)
        context['todo_list'] = Task.objects.filter(status='TD', board=self.object).order_by('-update_time')
        context['in_progress_list'] = Task.objects.filter(status='PR', board=self.object).order_by('-update_time')
        context['done_list'] = Task.objects.filter(status='DN', board=self.object).order_by('-create_time')
        return context


class TaskUpdateView(UpdateView):
    model = Task
    fields = ['title', 'text']
    http_method_names = ['post', 'get']
    template_name = 'task_edit.html'

    def get_success_url(self):
        return reverse_lazy('board:board_detail', kwargs={'pk': self.object.board.id})


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'task_confirm_delete.html'
    http_method_names = ['post', 'get']

    def get_success_url(self):
        return reverse_lazy('board:board_detail', kwargs={'pk': self.object.board.id})


class TaskCreateView(CreateView):
    model = Task
    fields = ['title', 'text']
    template_name = 'task_create.html'

    def form_valid(self, form):
        form.instance.board = Board.objects.get(pk=self.kwargs['board_pk'])
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('board:board_detail', kwargs={'pk': self.object.board.id})


class TaskMoveView(UpdateView):
    model = Task
    fields = ['status']
    http_method_names = ['post', 'get']
    template_name = 'task_edit.html'

    def get_success_url(self):
        return reverse_lazy('board:board_detail', kwargs={'pk': self.object.board.id})

lime/lime/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LoginView
from .forms import SignupForm, UserLoginForm


class UserLoginView(LoginView):
    authentication_form = UserLoginForm
    template_name = "auth/login.html"


#  Function views
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        form = SignupForm()
    return render(request, 'auth/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def home(request):
    return render(request, 'base.html')

lime/board/templates/base_board.html
{% extends 'base.html' %}

{% block content_block %}
    {% if user.is_authenticated %}
        <div>
            {% for board in board_list %}
            <a href="{% url 'board:board_detail' pk=board.pk %}"><h2>{{ board|upper|safe }}</h2></a>
            {% endfor %}
        </div>
    {% endif %}
    {% block board %}{% endblock %}
{% endblock %}

lime/board/templates/board_detail.html
{% extends 'base.html' %}

{% block content_block %}
    <h1>{{ board.title|safe }}</h1>
    <div class="container">
      <a href="{% url 'board:task_create' board_pk=board.pk %}" class="btn btn-primary" type="button">CREATE NEW TASK</a>
      <div class="row">
        <div class="col-sm">
          <h3>TO DO</h3>
            {% for task in todo_list %}
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">{{ task.title|safe }}</h5>
                    <p class="card-text">{{ task.text|safe }}</p>
                    <a href="{% url 'board:task_delete' pk=task.pk %}" class="btn btn-danger">DELETE</a>
                    <a href="{% url 'board:task_move' pk=task.pk %}" class="btn btn-primary">MOVE</a>
                      <a href="{% url 'board:task_edit' pk=task.pk %}" class="btn btn-success">EDIT</a>
                  </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-sm">
          <h3>In progress</h3>
            {% for task in in_progress_list %}
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">{{ task.title|safe }}</h5>
                    <p class="card-text">{{ task.text|safe }}</p>
                    <a href="{% url 'board:task_delete' pk=task.pk %}" class="btn btn-danger">DELETE</a>
                    <a href="{% url 'board:task_move' pk=task.pk %}" class="btn btn-primary">MOVE</a>
                      <a href="{% url 'board:task_edit' pk=task.pk %}" class="btn btn-success">EDIT</a>
                  </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-sm">
          <h3>Done</h3>
            {% for task in done_list %}
                <div class="card" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">{{ task.title|safe }}</h5>
                    <p class="card-text">{{ task.text|safe }}</p>
                    <a href="{% url 'board:task_delete' pk=task.pk %}" class="btn btn-danger">DELETE</a>
                    <a href="{% url 'board:task_move' pk=task.pk %}" class="btn btn-primary">MOVE</a>
                      <a href="{% url 'board:task_edit' pk=task.pk %}" class="btn btn-success">EDIT</a>
                  </div>
                </div>
            {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

lime/board/templates/task_confirm_delete.html
<form method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="DELETE">
    <a href="{% url 'board:board_detail' pk=object.board.pk %}" type="button" class="btn btn-success">BACK</a>
</form>

lime/board/templates/task_create.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

lime/board/templates/task_edit.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'board:board_detail' pk=object.board.pk %}" type="button" class="btn btn-success">BACK</a>
</form>

lime/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- BOOTSTRAP -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!--  MY CSS  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Scrum board</title>
</head>
<body>
    <header>
        <a class="text-decoration-none" href="{% url 'home' %}"><h1 id="main-title">Scrum board</h1></a>
            {% if user.is_authenticated %}
                <div class="row">
                    <div class="col-md-auto">
                        <p class="btn btn-primary">USER: {{ user.username }}</p>
                    </div>
                    <div class="col col-lg-2">
                        <a class="btn btn-warning justify-content-end" href="{% url 'logout' %}">Logout</a>
                    </div>
                    <div class="col col-lg-2">
                        <a class="btn btn-warning justify-content-end" href="{% url 'board:board_list' %}">{{ user.username }}'s boards</a>
                    </div>
                    <div class="col col-lg-2">
                        <a class="btn btn-warning justify-content-end" href="{% url 'board:board_create' %}">Create new board</a>
                    </div>
                </div>
            {% else %}
                <a href="{% url 'login' %}">
                    <button type="button" class="btn btn-primary">Sign In</button>
                </a>
                <a href="{% url 'signup' %}">
                    <button type="button" class="btn btn-warning">Sign Up</button>
                </a>
            {% endif %}
    </header>
    <section>{% block content_block %}{% endblock %}</section>
</body>
</html>